#! /usr/bin/env python

# Add auto-completion and a stored history file of commands to your Python
# interactive interpreter. Requires Python 2.0+, readline. Autocomplete is
# bound to the Esc key by default (you can change it - see readline docs).

import atexit
import os
import sys
import readline
import rlcompleter

# Set up history
historyPath = os.path.expanduser("~/.yolohistory")

def save_history(historyPath=historyPath):
    import readline
    readline.write_history_file(historyPath)

if os.path.exists(historyPath):
    readline.read_history_file(historyPath)

# Save history at end of session
atexit.register(save_history)

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
from scraper.ui import UI

interface = UI()
interface.loadStopWords(os.path.join(os.path.dirname(__file__), "../stop_words.txt"))
interface.run()

del os, atexit, readline, rlcompleter, save_history, historyPath
